<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Google-Suche</name>
   <tag></tag>
   <elementGuidId>5d0f590c-0257-4d4f-88a1-e90f5e0ba124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tsf&quot;]/div[2]/div/div[2]/div[2]/div[2]/center/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tsf&quot;]/div[2]/div/div[2]/div[2]/div[2]/center/input[1]</value>
   </webElementProperties>
</WebElementEntity>
