<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fehlermeldung</name>
   <tag></tag>
   <elementGuidId>30505111-0943-42fd-ae8e-c4ba81dc8cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='ctl00_ContentPlaceHolder1_MesswertEdit_MesswertValidationSummary']/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolder1_MesswertEdit_MesswertValidationSummary']/ul/li</value>
   </webElementProperties>
</WebElementEntity>
