<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstRow</name>
   <tag></tag>
   <elementGuidId>5eb378bd-5d93-4326-b22a-e9f3da6dd61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@data-ig='x:921019516.20:adr:0:tag:']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@data-ig='x:921019516.20:adr:0:tag:']/td</value>
   </webElementProperties>
</WebElementEntity>
