<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MesswertFieldReihe1</name>
   <tag></tag>
   <elementGuidId>77a71636-e1dd-48a4-aee0-73607d9d5c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@data-ig='x:921019516.23:val:3.2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[@data-ig='x:921019516.23:val:3.2']</value>
   </webElementProperties>
</WebElementEntity>
