<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThirdRow</name>
   <tag></tag>
   <elementGuidId>d6621571-9732-4913-8073-25da7a9f8c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@data-ig='x:921019516.20:adr:2:tag:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@data-ig='x:921019516.20:adr:2:tag:']</value>
   </webElementProperties>
</WebElementEntity>
