<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kontrollgang</name>
   <tag></tag>
   <elementGuidId>7242f1a3-31b7-4a0d-82a3-abfc4a0f239e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='ctl00_TreeView1t4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='ctl00_TreeView1t4']</value>
   </webElementProperties>
</WebElementEntity>
